# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# シェルのプロンプトの間に空行を挿入する
add_newline = true

# ref https://github.com/starship/starship/discussions/1107?sort=top#discussioncomment-10214050
format = """
[╭{owo} ](bold green)$username$directory$battery$all$line_break$character"""

[character]
success_symbol = '[╰─>](bold green)'
error_symbol = '[x >](bold red)'

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'

# ref https://zenn.dev/link/comments/ced6da507bf16f
[git_status]
format = '$all_status$ahead_behind '
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '[✓](bold green)'
untracked = ''
stashed = ''
modified = '🔥'
staged = ''
renamed = ''
deleted = ''

[python]
symbol = "🐍 "
style = "bold yellow"
pyenv_prefix = "pyenv "

[cmd_duration]
min_time = 500
style = "italic gray"
format = "took $duration "

[custom.obsidian]
command = "echo '📓'"
when = 'pwd | grep -i "$OBSIDIAN_VAULT_PATH"'
style = "bold magenta"

[time]
disabled = false
format = '🕙 [$time]($style) '
time_format = '%m/%d %R'

[aws]
disabled = true

[gcloud]
disabled = true